version: '3.8'

services:
  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.27.7
    ports:
      - 8080:8080
      - 50051:50051
    volumes:
      - ./weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_API_BASED_MODULES: 'true'
      CLUSTER_HOSTNAME: 'node1'
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8080"]
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 10s
    networks:
      - shared_network

  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 10s
    networks:
      - shared_network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: api
    depends_on:
      mongodb:
        condition: service_healthy
      weaviate:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    entrypoint:
      - /bin/bash
      - -c
      - |
        python create_dbs.py && uvicorn app:app --host 0.0.0.0 --port 8000
    networks:
      - shared_network

volumes:
  weaviate_data:
  mongo_data:

networks:
  shared_network:
    driver: bridge
